### ISSUE TITLE
src/keypad_sensor.h:21:37: error: 'GPIO25' was not declared in this scope

### ISSUE THREAD

**Issue by koenkv** [Syralist/esphomekeypad#1]
Hello,

I changed the pins to GPIO
and I get the following errors

Compiling /data/test_keypad/.pioenvs/test_keypad/lib0d3/ESP8266mDNS/LEAmDNS_Transfer.cpp.o
In file included from src/main.cpp:14:0:
src/keypad_sensor.h:20:29: error: 'GPIO34' was not declared in this scope
     byte colPins[n_cols] = {GPIO34, GPIO35, GPIO32};
src/keypad_sensor.h:20:37: error: 'GPIO35' was not declared in this scope
     byte colPins[n_cols] = {GPIO34, GPIO35, GPIO32};
src/keypad_sensor.h:20:45: error: 'GPIO32' was not declared in this scope
     byte colPins[n_cols] = {GPIO34, GPIO35, GPIO32};
src/keypad_sensor.h:21:29: error: 'GPIO33' was not declared in this scope
     byte rowPins[n_rows] = {GPIO33, GPIO25, GPIO26, GPIO27};
src/keypad_sensor.h:21:37: error: 'GPIO25' was not declared in this scope
     byte rowPins[n_rows] = {GPIO33, GPIO25, GPIO26, GPIO27};
src/keypad_sensor.h:21:45: error: 'GPIO26' was not declared in this scope
     byte rowPins[n_rows] = {GPIO33, GPIO25, GPIO26, GPIO27};
src/keypad_sensor.h:21:53: error: 'GPIO27' was not declared in this scope
     byte rowPins[n_rows] = {GPIO33, GPIO25, GPIO26, GPIO27};
*** [/data/test_keypad/.pioenvs/test_keypad/src/main.cpp.o] Error 1

How to fix it

**Comment by Syralist** [comment]
Are you using a esp8266 or esp32 microcontroller?

**Comment by koenkv** [comment]
i'm using a esp32

**Comment by Syralist** [comment]
For esp32 you have to write only the number. E.g. 25 in stead of GPIO25.

**Comment by koenkv** [comment]
Now it is working thank you very much

**Comment by Protoncek** [comment]
I know that topic is closed, but i hope that you can help me: can you please explain a bit more about this? I'm kinda noob here and don't knpow how to define pins. I have ESP8266 board, i copied *.h files into my esphome folder, but i keep getting errors in ESPHome that pins D1 ... thourgh D7 are not defined. How-where to define them? I changed names to GPIO, but then i get error that GPIOx is not defined...
Ok extension for this would be how to define pins on sx1509 extension board...

**Comment by Syralist** [comment]
On Arduino boards the pins are addressed with the names GPIOx. On ESP8266 boards the pins are addressed with the names Dx like they are labelled on the board. And normally you don't have to do anything, it just works. Can you maybe share your yaml file?
I can't say anything about the sx1509.

**Comment by Protoncek** [comment]
Thanks for reply!
My yaml is pretty much like yours "keypadtext.yaml", except my boards is stated: "board: esp01_1m". I assume that's the reason that i was getting errors - by removing letter "D" in *.h file compile goes through fine

` byte colPins[n_cols] = {12, 13, 14};`
` byte rowPins[n_rows] = {4, 5, 0, 2};`

i assumed that GPIO1 -->1, GPIO2 -->2 etc... but keypad still doesn't work. In ESPLog i get random messages 
`[D][text_sensor:015]: 'Keypad TextSensor': Sending state ''`
So i wonder - should i put any pullup resistors anywhere? Which pins are suppose to be inputs - cols or rows? I assume that whole thing "catches" some kind of uncertain states...

[esp-201.zip](https://github.com/Syralist/esphomekeypad/files/6273539/esp-201.zip)

**Comment by Syralist** [comment]
Maybe it's a problem with the board you specified. From what i see on Google the esp01 is the bare board without the double pin rows and the USB connector. When i talk about esp8266 i usually mean wemos d1 mini or nodemcu. 
Maybe on your board the pins have different names. I never used this unfortunately. 
As for wiring, i didn't have to use resistors and the keypad library handles the input output definition.

**Comment by Protoncek** [comment]
I think i found out  why it didn't work: tow things:
- it DOES MATTER which pins are inputs and which are outputs! Pins, which are required to have a certain state at bootup MUST be outputs or keypad doesn't work! So, my working config is this:

`byte colPins[n_cols] = {15, 0, 2}; //outputs`
`byte rowPins[n_rows] = {10, 14, 12, 13}; //inputs`

- Second thing: NOT ALL keypads with rubber contact are ok! I have one, which has pressed-key resisatance around 1kohm, which is too much, so sometimes works, but mostly it doesn't. A combo of those things made my headache... When i digged out a keypad with classic switches keypad works like a charm!

Do you have any idea/suggestion how/if i could define I/O expander pins instead of GPIO ones in *.h file? I'd use any expnder, MCP23107, PCF8754, SX1509... it doesn't matter, as long as it's expander, where in/out's are not so sensitive...

**Comment by Syralist** [comment]
good thing you figured it out! :)

i can't say anything about port expanders, i have never used those.
